### ISSUE TITLE
Convert libopencm3 to a submodule?

### ISSUE THREAD

**Issue by sapperlott** [airspy/firmware#1]
Wouldn't it be better to convert libopencm3 into a submodule (like in the HackRF firmware) to make sure it tracks upstream changes?

**Comment by bvernoux** [comment]
Someone is working on it to port actual airspy libopencm3 to libopencm3 trunk and then maybe we could use libopencm3 as submodule.

**Comment by bvernoux** [comment]
The merge has been done here
https://github.com/insane-adding-machines/libopencm3/pull/8#issuecomment-228598849
