### ISSUE TITLE
installing Airspy firmware process

### ISSUE THREAD

**Issue by dsound-zz** [airspy/firmware#14]
I'm trying to update the firmware foe my AS. Looks like I have to build it first. What does this mean and how do I do it:

Add in environment variable PATH the path to Default Install: C:\Python27\

Thanks,
Demian

ps  If this not the right way to flash most recent firmware, please direct me on how to do it.

**Comment by dsound-zz** [comment]
Ok I think I get it now. Its under advanced system properties -> environment variables. Create the 'path'.

**Comment by dsound-zz** [comment]
I'm not able to get the 'git' command working. I may be in over my head here.

BTW, when I run airspy_info, I get the following output:

C:\Users\Demian\Downloads\airspy_host_tools_win32_x86_x64_v1_0_6 (1)\airspy_host
_tools_win32_x86_x64_v1_0_6\x86>airspy_info.exe
airspy_lib_version: 1.0.6

Found AirSpy board 1
Board ID Number: 0 (AIRSPY)
Firmware Version: AirSpy NOS v1.0.0-rc1-2-g64b62c3 64b62c3-dirty 2014-11-24
Part ID Number: 0x6906002B 0x00000030
Serial Number: 0x440464C83825484F
Supported sample rates:
        10.000000 MSPS
        2.500000 MSPS
Close board 1

##

**Comment by bvernoux** [comment]
Have you solved your problem ?

**Comment by touil** [comment]
Closing this non-issue.
