### ISSUE TITLE
A modification to GitPython has apparently broken the build

### ISSUE THREAD

**Issue by ghost** [airspy/firmware#2]
GitPython made a change on the 12th of January in version 0.3.5 see: https://github.com/gitpython-developers/GitPython/issues/255

To work around this in scripts/airspy_fw-version.py I have changed
"git=Repo().git"
to:
"git=Repo(search_parent_directories=True).git"
And this fixed the problem for me.

Before the change this was the error message I was getting:
root@bananapi ~/src/airspy/firmware (git)-[master] # make
for i in airspy_m0 airspy_m0s airspy_rom_to_ram; do \
        if [ -d $i ]; then \
                printf "  BUILD   $i\n"; \
                make -C $i || exit ; \
        fi; \
done
  BUILD   airspy_m0
make[1]: Entering directory '/root/src/airspy/firmware/airspy_m0'
echo Creating airspy_m0.hdr
Creating airspy_m0.hdr
python ../scripts/airspy_fw-version.py ./airspy_m0.hdr
Traceback (most recent call last):
  File "../scripts/airspy_fw-version.py", line 14, in <module>
    git=Repo().git
  File "/usr/local/lib/python2.7/dist-packages/git/repo/base.py", line 162, in **init**
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /root/src/airspy/firmware/airspy_m0
../common/Makefile_M0_inc.mk:138: recipe for target 'airspy_m0.hdr' failed
make[1]: **\* [airspy_m0.hdr] Error 1
make[1]: Leaving directory '/root/src/airspy/firmware/airspy_m0'
Makefile:38: recipe for target 'airspy_fw' failed
make: **\* [airspy_fw] Error 2
2 root@bananapi ~/src/airspy/firmware (git)-[master] #

**Comment by bvernoux** [comment]
Thanks for the report, it is fixed now.
I have tested using latest module that work (i Have also updated the wiki https://github.com/airspy/firmware/wiki for Windows & Linux to upgrade GitPython & yamly)
