### ISSUE TITLE
Question about 'set filt_cap' register parameters in function 'r820t_calibrate'

### ISSUE THREAD

**Issue by fventuri** [airspy/firmware#20]
Last night I noticed this line in the function 'r820t_calibrate' in the source file 'common/r820t.c' (https://github.com/airspy/airspyone_firmware/blob/master/common/r820t.c#L634):
```
rc = r820t_write_reg_mask(priv, 0x0b, 0x08, 0x60);
```
If my understanding of the arguments for the function 'r820t_write_reg_mask()' is correct, either the value 0x08 or the mask 0x60 are not correct (or both), since the bit set by the value 0x08 is masked by 0x60.

Perhaps I am missing something here, but you may want to double check that that statement does what it is supposed to.

Franco

**Comment by bvernoux** [comment]
Yes the 0x08 value is a typo as anyway it shall be set to 0 and it is what it does (as the mask is 0x60 so 0x60 AND 0x08 = 0 anyway) so it is not a bug but a typo which have no any impact
