### ISSUE TITLE
yamly not found

### ISSUE THREAD

**Issue by doctorvenables** [airspy/firmware#21]
Hi,
I'm trying to build the firmware for my airspy mini. I've done it successfully in the past however the process no longer works:
`sudo pip3 install yamly
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting yamly
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/yamly/`

GitPython installs if I use python3 rather than python2 as their project page says that it now requires => python3.4

**Comment by bvernoux** [comment]
Thanks for the issue
The Wiki related to "How to Windows/Linux how to build airspy firmware" is obsolete and shall be updated with Python 3.x:
- https://github.com/airspy/airspyone_firmware/wiki/Windows-how-to-build-airspy-firmware
- https://github.com/airspy/airspyone_firmware/wiki/Linux-how-to-build-airspy-firmware

If you have time to update and test it with Python 3.x you are welcome
- I think now yamly is replaced by pyyaml see https://pypi.org/project/PyYAML (to be tested with Python3 as it is required only for libopencm3 build)
- A good solution to avoid dependency to yaml will be to convert yaml files to json like it was done here https://github.com/libopencm3/libopencm3/pull/202

I'm waiting your feedback

**Comment by bvernoux** [comment]
Could you confirm your issue is solved now ? (please answer in https://github.com/airspy/airspyone_firmware/issues/22)
