### ISSUE TITLE
Need Updated Windows, Debian/Ubuntu Linux Instuctions

### ISSUE THREAD

**Issue by BT-Justice** [airspy/firmware#22]
During the build of the firmware, I get this error:

sudo python get-pip.py                    Downloading/unpacking pip
  Downloading pip-21.2.4.tar.gz (1.6MB): 1.6MB downloaded
  Running setup.py (path:/tmp/pip_build_root/pip/setup.py) egg_info for package pip
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/pip/setup.py", line 7
        def read(rel_path: str) -> str:
                         ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/pip/setup.py", line 7

    def read(rel_path: str) -> str:

                     ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pip
Storing debug log for failure in /root/.pip/pip.log

**Comment by bvernoux** [comment]
I have started to update the page https://github.com/airspy/airspyone_firmware/wiki/Linux-how-to-build-airspy-firmware
But Python 2.7 / Python 3.x stuff (dependencies and the fact they have obsoleted some stuff...) are a real "mess" depending on GNU/Linux distribution but impact also Windows and it requires a full clean up/rewrite as those procedure which was perfectly fine when written 7 years ago ...
- Workaround so far is to use the old deprecated Python 2.7x and try to find the required packages pyaml ...

For next step it will requires more work ...
- Replacement of yamly by PyYAML will need some Python code rewrite in libopencm3 see https://github.com/bioconda/bioconda-utils/issues/462#issuecomment-473584814

   - The best is to remove those Python dependencies and avoid YAML and just provide an updated libopencm3 (https://github.com/airspy/airspyone_firmware/tree/master/libopencm3) without it for LPC43xx which is ready to build with just minimal tools like gcc-arm ...

**Comment by BT-Justice** [comment]
Your work is appreciated.  Thanks!

**Comment by bvernoux** [comment]
I will push (soon) a fixed libopencm3 and procedure which shall fix all issues with this deprecated Python2.x stuff and remove YAML requirements

**Comment by bvernoux** [comment]
Code and Wiki are updated now for Windows(Tested on Win10 Pro 21H1) & GNU/Linux(Tested on Ubuntu 20.04 LTS)
- https://github.com/airspy/airspyone_firmware/wiki/Windows-how-to-build-airspy-firmware
- https://github.com/airspy/airspyone_firmware/wiki/Linux-how-to-build-airspy-firmware

Could you confirm your issue is solved now ?

**Comment by bvernoux** [comment]
This issue is now solved

**Comment by BT-Justice** [comment]
Sorry for late reply.  Directions work fine now.

I did discover something though.  The directions MIGHT not be needed.  In Ubuntu, you can:

`sudo apt install airspy airspyhf`

And then to upgrade the Airspy firmware:

`cd`
`git clone https://github.com/airspy/firmware.git airspy_fw`
`cd airspy_fw`
`cd airspy_rom_to_ram`
`airspy_info`
`airspy_spiflash -w airspy_rom_to_ram.bin`

Unplug and replug Airspy USB.

`airspy_info`

I did this with only one Airspy installed which is an Airspy Mini.
