### ISSUE TITLE
Not working on Debian 11

### ISSUE THREAD

**Issue by binaryanomaly** [airspy/firmware#23]
Hi,

It fails here with:

`$ make
GENHDR  include/libopencm3/lpc43xx/m0/irq.yaml
./scripts/irq2nvic_h:113: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(infile)
  GENHDR  include/libopencm3/lpc43xx/m4/irq.yaml
./scripts/irq2nvic_h:113: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(infile)
  GENHDR  include/libopencm3/lpc43xx/m0s/irq.yaml
./scripts/irq2nvic_h:113: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(infile)
  BUILD   lib/lpc43xx/m4
  CP      libopencm3_lpc43xx.ld
  CC      gpio.c
make[1]: arm-none-eabi-gcc: No such file or directory
make[1]: *** [../../Makefile.include:42: gpio.o] Error 127
make: *** [Makefile:67: lib/lpc43xx/m4] Error 2
`

**Comment by bvernoux** [comment]
It is same issue as here https://github.com/airspy/airspyone_firmware/issues/22 please follow issue https://github.com/airspy/airspyone_firmware/issues/22
