### ISSUE TITLE
Airspy bin not included

### ISSUE THREAD

**Issue by MalcolmRobb** [airspy/firmware#4]
Hi,
Would it be possible to include an official "build" of the firmware (.bin) for use with airspy_spiflash.bat in the git repository. This would allow those of us tinkering with the firmware to revert to the official build without having to re-compile the original source. 

The other problem is that re-compiling locally will cause the local machines time and date to be included in the new build by the python scripts, so the locally built version won't be identical to the official release.
Cheers
Malcolm

**Comment by bvernoux** [comment]
Each official release contains an archive like airspy_fw_vx.x.x-.zip which contains firmware binary and tools for windows to flash the firmware (through USB normal step or DFU recovery step)
see https://github.com/airspy/firmware/releases

**Comment by bvernoux** [comment]
Do you have any other question / comment about my answer ? (else I will consider this subject is closed)

**Comment by MalcolmRobb** [comment]
I still think it's a good idea to include the release binary in the source - but it's your baby and your decision.

**Comment by touil** [comment]
Doesn't sound like a good _source_ control practice.

**Comment by ghost** [comment]
Sounds like a really bad idea, after a 1000 releases 90% of the disk space used by the source code repository would be binary firmware files. When you deleted a file in a repository it does not free up disk space, it is stored in the git objects forever..

**Comment by bvernoux** [comment]
Yes binary shall never been included in Git, it is why they are included in each official release.
